spring:
  application:
    name: @project.name@
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  profiles:
    active: h2
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: false
  jpa:
    open-in-view: false
sagra-service:
  cors:
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE
    allowed-origins:
      - http://localhost:3000
    max-age: 86400

---
spring:
  config:
    activate:
      on-profile: h2
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: test
  h2:
    console:
      enabled: true