spring:
  application:
    name: @project.name@
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: false
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: false
server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
sagra-service:
  cors:
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE
    allowed-origins:
      - http://localhost:3000
    max-age: 86400
    allow-credentials: true
  admin:
    name: Administrator

---
spring:
  config:
    activate:
      on-profile: h2
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: test
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  liquibase:
    drop-first: true
  sql:
    init:
      mode: never
sagra-service:
  admin:
    username: admin
    name: Administrator
    password: admin1234
