spring:
  application:
    name: "sagra-service"
  liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml
  profiles:
    active: h2
  jackson:
    default-property-inclusion: non_null
  mvc:
    log-resolved-exception: false
  jpa:
    open-in-view: false
sagra-service:
  cors:
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE
    allowed-origins:
      - '*'
    max-age: 86400
  service-cost: 0.5
  token-expire: 180

---
spring:
  config:
    activate:
      on-profile: h2
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: test
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  liquibase:
    drop-first: true
  sql:
    init:
      mode: never