services:
  mysql:
    image: mysql:8.4
    container_name: sagra-mysql
    environment:
      MYSQL_DATABASE: sagra
      MYSQL_USER: sagra
      MYSQL_PASSWORD: sagra
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql-data:/var/lib/mysql

  service:
    image: loreluc73/sagra-service:${SAGRA_SERVICE_VERSION}
    container_name: sagra-service
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sagra?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sagra
      SPRING_DATASOURCE_PASSWORD: sagra
      SERVER_ADDRESS: 0.0.0.0
      SAGRA_SERVICE_ADMIN_USERNAME: ${ADMIN_USERNAME}
      SAGRA_SERVICE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # SAGRA_SERVICE_CORS_ALLOWED_ORIGIN: "http://*:3000"
    ports:
      - "8080:8080"

  web:
    image: loreluc73/sagra-web:${SAGRA_WEB_VERSION}
    container_name: sagra-web
    depends_on:
      - service
    ports:
      - "3000:80"


volumes:
  mysql-data:
